# This workflow will build a Java project with Ant
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-ant

name: Java CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 19
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'

        ##Publicar no docker hub
    - uses: mr-smithers-excellent/docker-build-push@v6
    - name: Deploy Docker image
      with:
      ##coloca seu user do docker hub e nome da imagem que vc quer
        image: anabcruz/testepipeline
        tags: 1.0
        registry: docker.io
        dockerfile: Dockerfile
        username: ${{ secrets.DOCKERHUB_USER }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}


      
